name: Build TrResizer Extension

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'TrResizer/**'
      - '.github/workflows/build-trresizer.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'TrResizer/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Install or Update ImageMagick
      run: |
        # Check if ImageMagick is installed, upgrade if it is, install if not
        $installed = choco list --local-only imagemagick
        if ($installed -match "imagemagick") {
          Write-Host "ImageMagick already installed, upgrading..."
          choco upgrade imagemagick -y --no-progress
        } else {
          Write-Host "Installing ImageMagick..."
          choco install imagemagick -y --no-progress
        }
        # Set environment variable for ImageMagick
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
      shell: pwsh
    
    - name: Generate Icons
      working-directory: ./TrResizer
      run: |
        # Try different icon generation scripts
        if (Test-Path "generate-icons-from-svg.ps1") {
          Write-Host "Using generate-icons-from-svg.ps1"
          try {
            .\generate-icons-from-svg.ps1
          } catch {
            Write-Host "SVG generation failed, trying simple generation"
            if (Test-Path "generate-icons-simple.ps1") {
              .\generate-icons-simple.ps1
            } else {
              Write-Host "Warning: Could not generate icons, using existing ones"
            }
          }
        } elseif (Test-Path "generate-icons-simple.ps1") {
          Write-Host "Using generate-icons-simple.ps1"
          .\generate-icons-simple.ps1
        } elseif (Test-Path "generate-icons.ps1") {
          Write-Host "Using generate-icons.ps1 with fallback"
          .\generate-icons.ps1
        } else {
          Write-Host "Warning: No icon generation script found, using existing icons"
        }
      shell: pwsh
      continue-on-error: true
    
    - name: Build Simple Version
      working-directory: ./TrResizer
      run: |
        # Non-interactive build
        if (Test-Path "build-simple.ps1") {
          # Modify script temporarily to be non-interactive
          $script = Get-Content "build-simple.ps1" -Raw
          $script = $script -replace 'Read-Host.*', '$response = "n"'
          $script | Out-File "build-simple-ci.ps1" -Encoding UTF8
          .\build-simple-ci.ps1
        } else {
          Write-Host "build-simple.ps1 not found, creating basic build"
          # Fallback: create dist-simple manually
          New-Item -ItemType Directory -Force -Path "dist-simple"
          Copy-Item -Path "wwwroot\*" -Destination "dist-simple" -Recurse -Force
        }
      shell: pwsh
    
    - name: Build Blazor Version (Optional)
      working-directory: ./TrResizer
      run: |
        .\build-extension.ps1 -Browser all -Package
      shell: pwsh
      continue-on-error: true
    
    - name: Create Release Package
      working-directory: ./TrResizer
      run: |
        # Create release directory
        New-Item -ItemType Directory -Force -Path release
        
        # Check if dist-simple exists, if not create it
        if (-not (Test-Path dist-simple)) {
          Write-Host "dist-simple not found, creating from wwwroot"
          New-Item -ItemType Directory -Force -Path dist-simple
          Copy-Item -Path wwwroot\* -Destination dist-simple -Recurse -Force
        }
        
        # Package simple version
        if (Test-Path dist-simple) {
          Write-Host "Creating TrResizer-Simple.zip"
          Compress-Archive -Path dist-simple\* -DestinationPath release\TrResizer-Simple.zip -Force
        }
        
        # Package Chrome/Edge version if exists
        if (Test-Path dist\chrome-edge) {
          Write-Host "Creating TrResizer-ChromeEdge.zip"
          Compress-Archive -Path dist\chrome-edge\* -DestinationPath release\TrResizer-ChromeEdge.zip -Force
        } elseif (Test-Path dist-simple) {
          Write-Host "Using dist-simple for ChromeEdge package"
          Compress-Archive -Path dist-simple\* -DestinationPath release\TrResizer-ChromeEdge.zip -Force
        }
        
        # Package Firefox version if exists
        if (Test-Path dist\firefox) {
          Write-Host "Creating TrResizer-Firefox.zip"
          Compress-Archive -Path dist\firefox\* -DestinationPath release\TrResizer-Firefox.zip -Force
        }
        
        # Copy store assets
        if (Test-Path store-assets) {
          Write-Host "Creating TrResizer-StoreAssets.zip"
          Compress-Archive -Path store-assets\* -DestinationPath release\TrResizer-StoreAssets.zip -Force
        }
        
        # List created files
        Write-Host "Release packages created:"
        Get-ChildItem -Path release
      shell: pwsh
    
    - name: Upload Extension Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trresizer-extension
        path: |
          TrResizer/release/*.zip
          TrResizer/store-assets/*.png
        retention-days: 30
    
    - name: Upload Simple Version for Testing
      uses: actions/upload-artifact@v4
      with:
        name: trresizer-simple
        path: TrResizer/dist-simple/
        retention-days: 7
    
    # Optional: Create GitHub Release (only if files exist)
    - name: Check for Release Files
      id: check_files
      working-directory: ./TrResizer
      run: |
        if (Test-Path release/*.zip) {
          $files = Get-ChildItem release/*.zip
          if ($files.Count -gt 0) {
            echo "files_exist=true" >> $env:GITHUB_OUTPUT
            Write-Host "Found $($files.Count) release files"
          } else {
            echo "files_exist=false" >> $env:GITHUB_OUTPUT
            Write-Host "No release files found"
          }
        } else {
          echo "files_exist=false" >> $env:GITHUB_OUTPUT
          Write-Host "Release directory empty"
        }
      shell: pwsh
    
    - name: Create Tag
      if: steps.check_files.outputs.files_exist == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        $tagName = "trresizer-v${{ github.run_number }}"
        git tag $tagName -m "Auto-release $tagName"
        git push origin $tagName --force
      shell: pwsh
      continue-on-error: true
    
    - name: Create Release
      if: steps.check_files.outputs.files_exist == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: trresizer-v${{ github.run_number }}
        name: TrResizer Release ${{ github.run_number }}
        body: |
          Automated release of TrResizer extension
          
          ## Downloads
          - **TrResizer-Simple.zip** - Ready to use version
          - **TrResizer-ChromeEdge.zip** - Chrome/Edge version
          - **TrResizer-StoreAssets.zip** - Store submission assets
        draft: false
        prerelease: false
        files: |
          TrResizer/release/*.zip
        fail_on_unmatched_files: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true